Controllers/AttendanceController.cs
using Abp.Web.Mvc.Alerts;
using lifedashboard.Data;
using lifedashboard.Enums;
using lifedashboard.Models;
using lifedashboard.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace lifedashboard.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly DBConfig dB;

        public AttendanceController(DBConfig dB)
        {
            this.dB = dB;
        }
        [HttpGet]
        public IActionResult Attendance()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Attendance(PresentLog log)
        {
            PresentLog presentLog = new PresentLog()
            {
                Id = Guid.NewGuid(),
                Phone=log.Phone,
                AttendDate = DateTime.Now,
                Month=DateTime.Now.ToString("MMMM"),
                CreateDate= DateTime.Now,
                LastModifiedDate= DateTime.Now
            };
       
            var checkPhone = await dB.MemberDetails.FirstOrDefaultAsync(x => x.Phone == presentLog.Phone);
            if (checkPhone != null) 
            {
                try
                {
                    await dB.PresentLog.AddAsync(presentLog);
                    await dB.SaveChangesAsync();
                    ViewBag.Type = "Success";
                    ViewBag.ErrorMessage ="Data is saved" ;
                    //return RedirectToAction("Index", "Home");
                    return View();
                }
                catch(Exception e)
                {
                    ViewBag.Type = "Error";
                    ViewBag.ErrorMessage =e;
                    return View();
                }
               

            } 
            else
            { 
                ViewBag.Type = "Warning";
                ViewBag.ErrorMessage ="Member not found. Please contact the GYM administrator";
              
                return View();
            }

           


        }

    }
}

Controllers/DashBoardController.cs
using lifedashboard.Data;
using lifedashboard.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace lifedashboard.Controllers
{
    public class DashboardController : Controller
    {
        private readonly DBConfig dB;

        public DashboardController(DBConfig dB)
        {
            this.dB = dB;
        }
        [HttpGet]
        public IActionResult Dashboard(Dashboard dash)
        {
            var currentYear = DateTime.Now.Year;
            var currentMonth = DateTime.Now.Month;
            var currentDay = DateTime.Now.Day;

            dash.TotalMember = dB.MemberDetails.Count().ToString();
            dash.TotalRevenue = dB.FeeCollection.Sum(s => s.FeeAmount).ToString();
            dash.RevenueCurrentYear = dB.FeeCollection.Where(fee => fee.CreateDate.Year == currentYear).Sum(s => s.FeeAmount).ToString();
            dash.RevenueCurrentMonth = dB.FeeCollection.Where(m => m.CreateDate.Year == currentYear && m.CreateDate.Month == currentMonth).Sum(s => s.FeeAmount).ToString();

            dash.RevenueCurrentDay = dB.FeeCollection.Where(m => m.CreateDate.Year == currentYear && m.CreateDate.Month == currentMonth && m.CreateDate.Day == currentDay).Sum(s => s.FeeAmount).ToString();

            dash.MemberVisitedCurrentMonth = dB.PresentLog.Where(m => m.CreateDate.Year == currentYear && m.CreateDate.Month == currentMonth).Select(log => log.Phone).Distinct().Count().ToString();
           
            dash.MemberVisitedToday = dB.PresentLog.
                Where(m => m.CreateDate.Year == currentYear && m.CreateDate.Month == currentMonth && m.CreateDate.Day == currentDay)
                .Select(log => log.Phone)
                .Distinct()
                .Count()
                .ToString();

            dash.NewAdmissionCurrentMonth = dB.MemberDetails.Where(m => m.CreateDate.Year == currentYear && m.CreateDate.Month == currentMonth).Count().ToString(); 

            return View(dash);

        }
    }
}

Controllers/SearchPlansController.cs
using lifedashboard.Data;
using lifedashboard.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace lifedashboard.Controllers
{
    public class SearchPlansController : Controller
    {
        private readonly DBConfig db;
        public SearchPlansController(DBConfig Db)
        {
            this.db = Db;
        }


        [HttpGet]
        public IActionResult SearchPlans(string SearchString)
        {
           

            if (db.AddPlans == null)
            {
                return (Problem(@"No plans found. please use Add Plans tab for adding new routine / diet"));
            }

            var fetchPlan = from m in db.AddPlans
                             select m;

            if (!String.IsNullOrEmpty(SearchString))
            {
                SearchString = SearchString.Trim();
                //var fetchPlan = db.AddPlans.Where(p => p.Name!.Contains(SearchString)).ToList();
                //return View( fetchPlan);
                fetchPlan = db.AddPlans.Where(p => p.Name!.Contains(SearchString));
            }

            return View(fetchPlan.ToList());
            
        }

        [HttpPost]
        public ActionResult RedirectAction()
        {
            // Perform any necessary operations here

            // Redirect to another action or page
            return RedirectToAction("AddPlans", "AddPlans");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lifedashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lifedashboard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
             @*   <a class="navbar-brand" href="#">LIFE</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                          
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Membership" asp-action="Membership">Membership</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="FeeCollection" asp-action="FeeCollection">Fee Collection</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Attendance" asp-action="Attendance">Attendance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="ListMember" asp-action="ListMember">Member List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="SearchPlans" asp-action="SearchPlans">Search Plans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a>
                        </li>
                </ul>
                 </div>
              
            </div>
           
        </nav>
     
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lifedashboard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>